name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: --deny warnings
    steps:
    - uses: actions/checkout@v2
    - name: Setup FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3        
    - name: Build
      run: cargo build --all-targets --all-features
